version: '3'
services:
  client:
    build: './client'
    ports:
      - "3000:3000"

  userAuthServices:
    build: './userAuthServices'
    ports:
      - "3001:3000"
    depends_on: 
      - db
      - 

  postServices:
    build: './postServices'
    ports:
      - "3002:3000"
    depends_on: 
      - db
    

  profileServices:
    build: './profileServices'
    ports:
      - "3003:3000"
    depends_on: 
      - db
  
  db:
    image: mongo
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./web/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - userAuthServices
      - postServices
      - profileServices